// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGB-2p8AM8LT8dx_-Blk8hqquf1IvHqPs',
    appId: '1:534246399569:web:2fce803b921b7e30546270',
    messagingSenderId: '534246399569',
    projectId: 'aioapp-405323',
    authDomain: 'aioapp-405323.firebaseapp.com',
    storageBucket: 'aioapp-405323.appspot.com',
    measurementId: 'G-MB9BLNQQG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwig9HMtRUSYkgkK90RGhQ5G14ppTdazU',
    appId: '1:534246399569:android:5dea6010bf0b3dd6546270',
    messagingSenderId: '534246399569',
    projectId: 'aioapp-405323',
    storageBucket: 'aioapp-405323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tz5tJkGteGBkZe3-9iP-ruFi9nR2EaY',
    appId: '1:534246399569:ios:030efcd75ab8f8cf546270',
    messagingSenderId: '534246399569',
    projectId: 'aioapp-405323',
    storageBucket: 'aioapp-405323.appspot.com',
    iosClientId: '534246399569-5kptql6fv95ovp8ihbuqglb3tbgj43cf.apps.googleusercontent.com',
    iosBundleId: 'com.AIO.aio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tz5tJkGteGBkZe3-9iP-ruFi9nR2EaY',
    appId: '1:534246399569:ios:24625c79cf6f0685546270',
    messagingSenderId: '534246399569',
    projectId: 'aioapp-405323',
    storageBucket: 'aioapp-405323.appspot.com',
    iosBundleId: 'com.AIO.aio.RunnerTests',
  );
}
